---

- name: "Installing & configuring pkgs for new server"
  block:
    - name: "Installing pkgs"
      ansible.builtin.apt:
          name: 
          - "nginx"
          - "sysstat"
          state: "{{ 'present' if not pkgs_latest else 'latest'}}"
          update_cache: true
      become: true

    - name: "Creating nginx dirs"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/etc/nginx"
        - "/var/log/nginx"
        - "/data/nginx"
        - "/home/ubuntu1/kekdir"
      # notify:
      # - start nginx
      become: true
      when: check_nginx_version.stdout.find('nginx/') != -1
#     when: check_nginx_version.stdout.find('nginx') != -1 #version is empty - dir will be created
#     when: check_nginx_version.stdout.find('nginx') != 1 #version is NOT empty - dir will not be created


