
version: '3.5'
services:
    # Video bridge -2
  jvb2:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-stable-7439}
    container_name:  jitsi_jvb_2
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${JVB_PORT}:${JVB_PORT}/udp'
      - '8081:8081'
    volumes:
      - ${CONFIG}/jvb:/config:Z
    environment:
    - DOCKER_HOST_ADDRESS
    - XMPP_AUTH_DOMAIN
    - XMPP_INTERNAL_MUC_DOMAIN
    - XMPP_SERVER
    - JVB_AUTH_USER
    - JVB_AUTH_PASSWORD
    - JVB_BREWERY_MUC
    - JVB_PORT
    - JVB_TCP_HARVESTER_DISABLED
    - JVB_TCP_PORT
    - JVB_STUN_SERVERS
    - JVB_ENABLE_APIS
    - TZ
    networks:
      meet.jitsi:

networks:
    meet.jitsi:
        name: jitsi-network
